#ifndef KERNEL_VERSION_H
#define KERNEL_VERSION_H

#ifndef LYTH_KERNEL_VERSION
#define LYTH_KERNEL_VERSION "0.6.0"
#endif

#define LYTH_KERNEL_NAME "Lyth OS"
#define LYTH_KERNEL_ID "lyth"
#define LYTH_KERNEL_PRETTY_NAME LYTH_KERNEL_NAME " " LYTH_KERNEL_VERSION

#if LYTH_AUTOTEST_ENABLED
#define LYTH_KERNEL_BUILD_FLAVOR "autotest"
#else
#define LYTH_KERNEL_BUILD_FLAVOR "default"
#endif

#endif